# Workflow to trigger labels by keywords

name: Label Trigger

on:
  issue_comment:
    types: created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  assign:
    runs-on: ubuntu-latest
    if: github.event.comment.body == '#take'
    steps:

      # Assign
      - name: Assign
#         run: echo "Assign to ${{ github.event.comment.user.login }}"
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [ '${{ github.event.comment.user.login }}' ]
            })

  remove-label-help-wanted:
    runs-on: ubuntu-latest
    if: github.event.comment.body == '#take'
    steps:
      - name: Remove label help-wanted
        if: contains(github.event.issue.labels.*.name, 'help wanted')
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'help wanted'
            })

  remove-label-stalled:
    runs-on: ubuntu-latest
    if: github.event.comment.body == '#take'
    steps:
      - name: Remove label stalled
        if: github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'stalled')
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'stalled'
            })

  add-label-superseded:
    runs-on: ubuntu-latest
    if: github.event.comment.body == '#take'
    steps:
      - name: Add label superseded
        if: github.event.issue.pull_request && !contains(github.event.issue.labels.*.name, 'superseded')
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['superseded']
            })

#   take-action:
#     runs-on: ubuntu-latest
#     if: github.event.comment.body == '#take'
#     steps:
#       - name: Add tag
#         uses: actions/github-script@v3
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#           script: |
#             github.issues.addLabels({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               issue_number: context.issue.number,
#               labels: ['invalid']
#             })
#       - name: Add tag 2
#         uses: actions/github-script@v3
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#           script: |
#             github.issues.addLabels({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               issue_number: context.issue.number,
#               labels: ['question']
#             })
            
#   take-command:
#     runs-on: ubuntu-latest
#     if: github.event.comment.body == '#take'
#     steps:
#       - name: Add tag
#         run: |
#           curl \
#           -X POST \
#           -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#           -H "Accept: application/vnd.github.v3+json" \
#           https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
#           -d '{"labels":["bug"]}'
#       - name: Add tag 2
#         run: |
#           curl \
#           -X POST \
#           -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#           -H "Accept: application/vnd.github.v3+json" \
#           https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
#           -d '{"labels":["wontfix"]}'
